wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700432594.785704
    t:
      1:
      - 5
      - 53
      - 55
      - 95
      - 105
      2:
      - 5
      - 53
      - 55
      - 95
      - 105
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
