name: Evaluate the new Broda-man model
  
on:
  issue_comment: 
  
permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  BRODAMAN_COMMENT: "/brodaman"

jobs:
  evaluate-model:
    if: github.event.issue.pull_request != null
    runs-on: windows-latest
    steps:
      - name: See payload
        run: echo "PAYLOAD:\n${PAYLOAD}\n"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}

      - name: Get repo contents
        uses: actions/checkout@v4

      - name: Filter for Broda-man comment
        id: filter
        if: contains(github.event.comment.body, env.BRODAMAN_COMMENT)
        run: echo "Broda-man comment detected"

      - name: Parse value from the command
        if: steps.filter.outcome == 'success'
        id: get-magic-value
        shell: python
        run: |
          import re, os
          comment = os.getenv('PR_COMMENT', '')
          match = re.search('${{ env.BRODAMAN_COMMENT }}[\s+](\S+)', comment)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            if match:
              print(f'VAL_FOUND=true', file=f)
              print(f'MAGIC_VAL={match.group(1)}', file=f)
            else:
              print(f'VAL_FOUND=false', file=f)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}

      - name: Print value of command
        if: steps.get-magic-value.outcome == 'success' && steps.get-magic-value.outputs.VAL_FOUND == 'true'
        run: echo "BRODAMAN_FINETUNE_MODEL_SUFFIX = ${{ steps.get-magic-value.outputs.MAGIC_VAL }}"

      - name: Install dependencies
        id: installations-and-evaluation
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python src/eval.py

      - name: Generate the evaluation report
        if: steps.installations-and-evaluation.outcome == 'success'
        id: export-link
        shell: python
        run: |
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f'RUN_FINISHED=true', file=f)
            print(f'WANDB_LINK={os.environ["WANDB_LINK"]}', file=f)

      - name: Print link
        if: steps.installations-and-evaluation.outcome == 'success' && steps.export-link.outputs.RUN_FINISHED == 'true'
        run: echo "WANDB_LINK = ${{ steps.export-link.outputs.WANDB_LINK }}"

      - name: Make a comment with the ghapi
        uses: actions/github-script@v6
        if: steps.get-magic-value.outcome == 'success'
        with:
          script: |
            var msg = `👋 Hi, this is 🅱🅻🅰🆀. An evaluation of the new model for Broda-man is available in this [report](${WANDB_LINK})`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
        env:
          WANDB_LINK: "${{ steps.installations-and-evaluation.outputs.WANDB_LINK }}"
