name: Evaluate the new Broda-man model

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  BRODAMAN_COMMENT: "/brodaman"

jobs:
  evaluate-model:
    if: github.event.issue.pull_request != null
    runs-on: windows-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: See payload
        run: echo "PAYLOAD:\n${PAYLOAD}\n"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}

      - name: Get repo contents
        uses: actions/checkout@v4

      - name: Filter for Broda-man comment
        id: filter
        if: contains(github.event.comment.body, env.BRODAMAN_COMMENT)
        run: echo "Broda-man comment detected"

      - name: Parse value from the command
        if: steps.filter.outcome == 'success'
        id: get-model-id
        shell: python
        run: |
          import re, os
          comment = os.getenv('PR_COMMENT', '')
          match = re.search('${{ env.BRODAMAN_COMMENT }}[\s+](\S+)', comment)
          with open(os.environ['GITHUB_ENV'], 'a') as f:
            if match:
              print(f'VAL_FOUND=true', file=f)
              print(f'MODEL_ID={match.group(1)}', file=f)
            else:
              print(f'VAL_FOUND=false', file=f)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}

      - name: Print value of command
        if: steps.get-model-id.outcome == 'success' && steps.get-model-id.outputs.VAL_FOUND == 'true'
        run: |
          echo "BRODAMAN_FINETUNE_MODEL_ID = ${{ steps.get-model-id.outputs.MODEL_ID }}"

      - name: Install dependencies
        id: installations-and-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run evaluation script
        id: eval-stage
        if: steps.installations-and-dependencies.outcome == 'success' && steps.get-model-id.outcome == 'success'
        run: |
          run = wandb.init(project="Your_Project_Name")
          python src/eval.py
          WANDB_link = run.get_url()
          echo "WANDB_link=$WANDB_link" >> $GITHUB_ENV

      - name: Make a comment with the ghapi
        uses: actions/github-script@v6
        if: steps.eval-stage.outcome == 'success'
        with:
          script: |
            var msg = `👋 Hi, this is 🅱🅻🅰🆀. An evaluation of the new model for Broda-man is available [here]($WANDB_link)`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
  
      - name: End the Workflow
        run: |
          echo "Workflow completed successfully."
