name: Evaluate the new Broda-man model

on: 
  issue_comment

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  BRODAMAN_COMMENT: '/brodaman'

jobs:
  evaluate-model:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/brodaman')
    runs-on: windows-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: See payload
        run: echo "PAYLOAD:\n${PAYLOAD}\n"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}

      - name: Get repo contents
        uses: actions/checkout@v4

      - name: Filter for Broda-man comment
        id: filter
        if: contains(github.event.comment.body, env.BRODAMAN_COMMENT)
        run: echo "Broda-man comment detected"

      - name: Parse value from the command
        if: steps.filter.outcome == 'success'
        id: get-magic-value
        shell: python
        run: |
          import re, os
          comment = os.getenv('PR_COMMENT', '')
          match = re.search(r'${{ env.BRODAMAN_COMMENT }}\s+(\S+)', comment)
          if match:
            print(f"::set-output name=MAGIC_VAL::{match.group(1)}")
            print(f"::set-output name=VAL_FOUND::true")
          else:
            print("::set-output name=VAL_FOUND::false")
        env:
          PR_COMMENT: ${{ github.event.comment.body }}

      - name: Print value of command
        if: steps.get-magic-value.outputs.VAL_FOUND == 'true'
        run: echo "BRODAMAN_FINETUNE_MODEL_ID = ${{ steps.get-magic-value.outputs.MAGIC_VAL }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
  
      - name: Run evaluation script
        run: |
          python src/eval.py
        env:
          BRODAMAN_FINETUNE_MODEL_ID: ${{ steps.get-magic-value.outputs.MAGIC_VAL }}

      - name: Upload evaluation results as an artifact
        if: steps.eval-stage.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: evaluation-results
          path: evaluation_results.json

      - name: Read Weights & Biases run link
        id: read-wandb-link
        run: |
          $wandbLink = Get-Content -Path wandb_link.txt -Raw
          echo "::set-output name=WANDB_LINK::$wandbLink"
        shell: pwsh

      - name: Make a comment with the ghapi
        if: steps.eval-stage.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            var wandbLink = "${{ steps.read-wandb-link.outputs.WANDB_LINK }}";
            var artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts`;
            var msg = `👋 Hi, this is 🅱🅻🅰🆀. An evaluation of the new model for Broda-man is available [here](${wandbLink}). You can download the evaluation results [here](${artifactUrl}).`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
