name: Broda-man CI/CD

on:
  push:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ci-cd-job:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.0

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Parse Model ID from Comment
        id: parse-model-id
        run: |
          comment_body="${{ github.event.comment.body }}"
          model_id_regex="/broda-man ft:gpt-3\.5-turbo-0613:personal:broda-man:\S+"
          if [[ $comment_body =~ $model_id_regex ]]; then
            model_id="${BASH_REMATCH[0]#'/broda-man '}"  # Remove the prefix
            echo "::set-env name=MODEL_ID::${model_id}"
          fi

      - name: Generate and Train Broda-man
        run: python src/generate_and_train_broda_man.py

      - name: Check Job Status
        id: job-status
        run: |
          status=$(python src/job_status.py)
          echo "::set-output name=status::$status"

  continue-with-the-rest:
    if: >
      github.event_name == 'issue_comment' &&
      github.event.action == 'created' &&
      github.event.issue.pull_request != null &&
      needs.ci-cd-job.outputs.status == 'succeeded'
    runs-on: windows-latest

    steps:
      - name: Continue with Scripts
        run: |
          echo "Job succeeded! Model ID is $MODEL_ID"
          export BRODAMAN_FINETUNE_MODEL_ID=$MODEL_ID
          export BRODAMAN_FINETUNE_JOB_ID=$JOB_ID
          python src/gen_eval_dataset.py
          python src/evaluate_broda_man_smoothing_function.py
          python src/gradio_web_service_interface.py

      - name: Make Comment on GitHub
        uses: actions/github-script@v6
        with:
          script: |
            var msg = `Broda-man is ready. You can interact with the service [here](http://127.0.0.1:7860?model_id=${process.env.BRODAMAN_FINETUNE_MODEL_ID})`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
